# Generated by Django 5.1.6 on 2025-03-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banker_app', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('categeory', models.CharField(max_length=60)),
                ('decribe', models.CharField(max_length=500)),
            ],
        ),
    ]
